from enum import Enum


class ValidationReasonCode(str, Enum):
    # ---------- Identity ----------
    INVALID_FIRST_NAME = "INVALID_FIRST_NAME"
    INVALID_LAST_NAME = "INVALID_LAST_NAME"

    INVALID_SSN_FORMAT = "INVALID_SSN_FORMAT"
    INVALID_SSN_LAST4 = "INVALID_SSN_LAST4"

    INVALID_DOB_FORMAT = "INVALID_DOB_FORMAT"
    AGE_BELOW_MINIMUM = "AGE_BELOW_MINIMUM"

    # ---------- Contact ----------
    INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT"
    INVALID_PHONE_FORMAT = "INVALID_PHONE_FORMAT"

    # ---------- Address ----------
    INVALID_ADDRESS_LINE = "INVALID_ADDRESS_LINE"
    INVALID_CITY = "INVALID_CITY"
    INVALID_STATE_CODE = "INVALID_STATE_CODE"
    INVALID_ZIP_FORMAT = "INVALID_ZIP_FORMAT"

    # ---------- Employment ----------
    INVALID_EMPLOYMENT_TYPE = "INVALID_EMPLOYMENT_TYPE"
    INVALID_EMPLOYER_NAME = "INVALID_EMPLOYER_NAME"
    INVALID_JOB_TITLE = "INVALID_JOB_TITLE"
    INVALID_MONTHLY_INCOME = "INVALID_MONTHLY_INCOME"

    # ---------- Loan ----------
    INVALID_LOAN_AMOUNT = "INVALID_LOAN_AMOUNT"
    INVALID_LOAN_TERM = "INVALID_LOAN_TERM"
