from enum import Enum


class ValidationReasonCode(str, Enum):
    # Identity
    INVALID_SSN_FORMAT = "INVALID_SSN_FORMAT"
    INVALID_DOB_FORMAT = "INVALID_DOB_FORMAT"
    AGE_BELOW_MINIMUM = "AGE_BELOW_MINIMUM"

    # Contact
    INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT"
    INVALID_PHONE_FORMAT = "INVALID_PHONE_FORMAT"

    # Address
    INVALID_ZIP_FORMAT = "INVALID_ZIP_FORMAT"
    CITY_ZIP_MISMATCH = "CITY_ZIP_MISMATCH"

    # Employment
    INVALID_EMPLOYER_NAME = "INVALID_EMPLOYER_NAME"
    INVALID_INCOME_VALUE = "INVALID_INCOME_VALUE"
