"""document type update

Revision ID: 083026c8fdd6
Revises: d6246ae57292
Create Date: 2026-02-03 13:08:13.595357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083026c8fdd6'
down_revision: Union[str, Sequence[str], None] = 'd6246ae57292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pgsqldocument', sa.Column('document_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pgsqldocument', 'document_type')
    # ### end Alembic commands ###
