"""new table metadata

Revision ID: 0c2613fc9ab8
Revises: b985fb7694d2
Create Date: 2026-02-03 11:06:53.849838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2613fc9ab8'
down_revision: Union[str, Sequence[str], None] = 'b985fb7694d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('accept_language', sa.String(length=200), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_metadata_app_id'), 'request_metadata', ['app_id'], unique=False)
    op.create_index(op.f('ix_request_metadata_created_at'), 'request_metadata', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_metadata_request_id'), 'request_metadata', ['request_id'], unique=True)
    op.drop_table('test_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_model_pkey'))
    )
    op.drop_index(op.f('ix_request_metadata_request_id'), table_name='request_metadata')
    op.drop_index(op.f('ix_request_metadata_created_at'), table_name='request_metadata')
    op.drop_index(op.f('ix_request_metadata_app_id'), table_name='request_metadata')
    op.drop_table('request_metadata')
    # ### end Alembic commands ###
