"""new human in loop table

Revision ID: 1a1ce6612ea2
Revises: 33cb05869aee
Create Date: 2026-02-09 14:34:10.276794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a1ce6612ea2'
down_revision: Union[str, Sequence[str], None] = '33cb05869aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

applicant_status_enum = postgresql.ENUM(
    'DRAFT',
    'SUBMITTED',
    'UNDER_REVIEW',
    'REVISION_REQUIRED',
    'APPROVED',
    'REJECTED',
    name='applicant_status_enum'
)

def upgrade() -> None:
    
    # ### end Alembic commands ###
     # 1️⃣ Create ENUM type first
    applicant_status_enum.create(op.get_bind(), checkfirst=True)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_review',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', name='human_decision_enum'), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_application.application_id'], name='fk_human_review_application', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='human_review_pkey')
    )
    # op.add_column('loan_application', sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'REVISION_REQUIRED', 'APPROVED', 'REJECTED', name='applicant_status_enum'), server_default=sa.text("'SUBMITTED'"), nullable=False))
    
    # 2️⃣ Add column using the enum
    op.add_column(
        'loan_application',
        sa.Column(
            'status',
            applicant_status_enum,
            nullable=False,
            server_default=sa.text("'SUBMITTED'")
        )
    )

def downgrade()-> None:
    # 1️⃣ Drop column first
    op.drop_column('loan_application', 'status')

    # 2️⃣ Drop enum
    applicant_status_enum.drop(op.get_bind(), checkfirst=True)
