"""added column in the document

Revision ID: 1ce0c66d3b52
Revises: 7d0eb0a6f0ad
Create Date: 2026-02-02 13:10:35.151442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce0c66d3b52'
down_revision: Union[str, Sequence[str], None] = '7d0eb0a6f0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('last_modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'last_modified_at')
    # ### end Alembic commands ###
