"""check

Revision ID: 229a259c2165
Revises: 1e7f54cad5e9
Create Date: 2026-02-03 11:23:26.229560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229a259c2165'
down_revision: Union[str, Sequence[str], None] = '1e7f54cad5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_model', sa.Column('text', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_model', 'text')
    # ### end Alembic commands ###
