"""checkdelete

Revision ID: 2eedab2c4924
Revises: 229a259c2165
Create Date: 2026-02-03 11:23:56.754399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eedab2c4924'
down_revision: Union[str, Sequence[str], None] = '229a259c2165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_model', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_model', sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
