"""relation setup

Revision ID: 5a1e147a25bc
Revises: 732ede14bd06
Create Date: 2026-02-02 19:31:47.137110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a1e147a25bc'
down_revision: Union[str, Sequence[str], None] = '732ede14bd06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_metadata_app_id'), table_name='request_metadata')
    op.drop_index(op.f('ix_request_metadata_created_at'), table_name='request_metadata')
    op.drop_index(op.f('ix_request_metadata_request_id'), table_name='request_metadata')
    op.drop_table('request_metadata')
    op.drop_column('pgsqldocument', 'document_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pgsqldocument', sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_table('request_metadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('browser', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('os', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accept_language', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('referrer', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('request_metadata_pkey'))
    )
    op.create_index(op.f('ix_request_metadata_request_id'), 'request_metadata', ['request_id'], unique=True)
    op.create_index(op.f('ix_request_metadata_created_at'), 'request_metadata', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_metadata_app_id'), 'request_metadata', ['app_id'], unique=False)
    # ### end Alembic commands ###
