"""intial setup

Revision ID: 7d0eb0a6f0ad
Revises: 
Create Date: 2026-02-02 13:04:33.746915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d0eb0a6f0ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_table('callback_status',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('callback_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='callback_status_pkey'),
    sa.UniqueConstraint('request_id', name='callback_status_request_id_key')
    )
    op.create_table('intake_idempotency',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('request_id', name='intake_idempotency_pkey')
    )
    op.create_table('loan_application',
    sa.Column('application_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('loan_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('credit_type', sa.String(length=20), nullable=True),
    sa.Column('loan_purpose', sa.String(length=50), nullable=True),
    sa.Column('requested_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('requested_term_months', sa.Integer(), nullable=True),
    sa.Column('preferred_payment_day', sa.Integer(), nullable=True),
    sa.Column('origination_channel', sa.String(length=20), nullable=True),
    sa.Column('application_status', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("credit_type::text = ANY (ARRAY['individual'::character varying, 'joint'::character varying]::text[])", name='loan_application_credit_type_check'),
    sa.CheckConstraint('preferred_payment_day >= 1 AND preferred_payment_day <= 28', name='loan_application_preferred_payment_day_check'),
    sa.CheckConstraint('requested_amount > 0::numeric', name='loan_application_requested_amount_check'),
    sa.PrimaryKeyConstraint('application_id', name='loan_application_pkey')
    )
    op.create_table('applicant',
    sa.Column('applicant_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('applicant_role', sa.String(length=20), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('suffix', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ssn_encrypted', sa.Text(), nullable=True),
    sa.Column('ssn_last4', sa.CHAR(length=4), nullable=True),
    sa.Column('itin_number', sa.String(length=15), nullable=True),
    sa.Column('citizenship_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("applicant_role::text = ANY (ARRAY['primary'::character varying, 'co_applicant'::character varying]::text[])", name='applicant_applicant_role_check'),
    sa.ForeignKeyConstraint(['application_id'], ['loan_application.application_id'], name='fk_applicant_application', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('applicant_id', name='applicant_pkey'),
    sa.UniqueConstraint('email', name='uq_applicant_email')
    )
    op.create_table('document',
    sa.Column('document_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['loan_application.application_id'], name='fk_document_application', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', name='document_pkey')
    )
    op.create_table('address',
    sa.Column('address_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=50), server_default=sa.text("'USA'::character varying"), nullable=True),
    sa.Column('housing_status', sa.String(length=30), nullable=True),
    sa.Column('monthly_housing_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('years_at_address', sa.Integer(), nullable=True),
    sa.Column('months_at_address', sa.Integer(), nullable=True),
    sa.Column('address_verified', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.CheckConstraint("address_type::text = ANY (ARRAY['current'::character varying, 'permanent'::character varying, 'mailing'::character varying]::text[])", name='address_address_type_check'),
    sa.CheckConstraint("housing_status::text = ANY (ARRAY['own'::character varying, 'rent'::character varying]::text[])", name='address_housing_status_check'),
    sa.CheckConstraint('months_at_address >= 0 AND months_at_address <= 11', name='address_months_at_address_check'),
    sa.CheckConstraint('years_at_address >= 0 AND years_at_address <= 50', name='address_years_at_address_check'),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.applicant_id'], name='fk_address_applicant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address_id', name='address_pkey')
    )
    op.create_table('asset',
    sa.Column('asset_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ownership_type', sa.String(length=20), nullable=True),
    sa.Column('asset_verified', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.CheckConstraint("ownership_type::text = ANY (ARRAY['individual'::character varying, 'joint'::character varying]::text[])", name='asset_ownership_type_check'),
    sa.CheckConstraint('value >= 0::numeric', name='asset_value_check'),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.applicant_id'], name='fk_asset_applicant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', name='asset_pkey')
    )
    op.create_table('employment',
    sa.Column('employment_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('employment_type', sa.String(length=30), nullable=True),
    sa.Column('employment_status', sa.String(length=20), nullable=True),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('employer_phone', sa.String(length=20), nullable=True),
    sa.Column('employer_address', sa.Text(), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('self_employed_flag', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('family_employment', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('gross_monthly_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('employment_verified', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.CheckConstraint('experience >= 0', name='employment_experience_check'),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.applicant_id'], name='fk_employment_applicant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employment_id', name='employment_pkey')
    )
    op.create_table('income',
    sa.Column('income_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('income_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('income_frequency', sa.String(length=20), nullable=True),
    sa.CheckConstraint('monthly_amount >= 0::numeric', name='income_monthly_amount_check'),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.applicant_id'], name='fk_income_applicant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('income_id', name='income_pkey')
    )
    op.create_table('liability',
    sa.Column('liability_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('liability_type', sa.String(length=50), nullable=True),
    sa.Column('creditor_name', sa.String(length=255), nullable=True),
    sa.Column('outstanding_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('monthly_payment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('months_remaining', sa.Integer(), nullable=True),
    sa.Column('co_signed', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('federal_debt', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('delinquent_flag', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('days_delinquent', sa.Integer(), nullable=True),
    sa.CheckConstraint('days_delinquent >= 0', name='liability_days_delinquent_check'),
    sa.CheckConstraint('monthly_payment >= 0::numeric', name='liability_monthly_payment_check'),
    sa.CheckConstraint('months_remaining >= 0', name='liability_months_remaining_check'),
    sa.CheckConstraint('outstanding_balance >= 0::numeric', name='liability_outstanding_balance_check'),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.applicant_id'], name='fk_liability_applicant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('liability_id', name='liability_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liability')
    op.drop_table('income')
    op.drop_table('employment')
    op.drop_table('asset')
    op.drop_table('address')
    op.drop_table('document')
    op.drop_table('applicant')
    op.drop_table('loan_application')
    op.drop_table('intake_idempotency')
    op.drop_table('callback_status')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
