"""Added new column

Revision ID: acf71b8af4e8
Revises: f280c16c5ccd
Create Date: 2026-02-02 15:33:02.873879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf71b8af4e8'
down_revision: Union[str, Sequence[str], None] = 'f280c16c5ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pgsqldocument', 'document_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PAN', 'AADHAAR', 'PASSPORT', 'DRIVER_LICENSE', 'BANK_STATEMENT', 'PAY_SLIP', name='document_type_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pgsqldocument', 'document_type',
               existing_type=sa.Enum('PAN', 'AADHAAR', 'PASSPORT', 'DRIVER_LICENSE', 'BANK_STATEMENT', 'PAY_SLIP', name='document_type_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
