"""col correction 2

Revision ID: d85d179ba7c2
Revises: b31327225042
Create Date: 2026-02-09 15:48:25.974451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd85d179ba7c2'
down_revision: Union[str, Sequence[str], None] = 'b31327225042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loan_application', 'application_status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'REVISION_REQUIRED', 'APPROVED', 'REJECTED', name='applicant_status_enum'),
               nullable=False)
    op.drop_column('loan_application', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_application', sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'REVISION_REQUIRED', 'APPROVED', 'REJECTED', name='applicant_status_enum'), server_default=sa.text("'SUBMITTED'::applicant_status_enum"), autoincrement=False, nullable=False))
    op.alter_column('loan_application', 'application_status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'REVISION_REQUIRED', 'APPROVED', 'REJECTED', name='applicant_status_enum'),
               nullable=True)
    # ### end Alembic commands ###
