"""add document classification metadata

Revision ID: e04dae7089a5
Revises: ecd4029c4424
Create Date: 2026-02-05 14:33:49.672410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04dae7089a5'
down_revision: Union[str, Sequence[str], None] = 'ecd4029c4424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pgsqldocument', sa.Column('document_confidence', sa.Float(), nullable=True))
    op.add_column('pgsqldocument', sa.Column('classification_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pgsqldocument', 'classification_method')
    op.drop_column('pgsqldocument', 'document_confidence')
    # ### end Alembic commands ###
