"""add image quality metadata to document

Revision ID: ecd4029c4424
Revises: 083026c8fdd6
Create Date: 2026-02-04 12:27:08.159245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecd4029c4424'
down_revision: Union[str, Sequence[str], None] = '083026c8fdd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1️⃣ Add column as nullable
    op.add_column(
        'pgsqldocument',
        sa.Column('is_low_quality', sa.Boolean(), nullable=True)
    )

    op.add_column(
        'pgsqldocument',
        sa.Column('quality_metadata', sa.dialects.postgresql.JSONB(), nullable=True)
    )

    # 2️⃣ Backfill existing rows
    op.execute(
        "UPDATE pgsqldocument SET is_low_quality = FALSE WHERE is_low_quality IS NULL"
    )

    # 3️⃣ Enforce NOT NULL constraint
    op.alter_column(
        'pgsqldocument',
        'is_low_quality',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pgsqldocument', 'quality_metadata')
    op.drop_column('pgsqldocument', 'is_low_quality')
    # ### end Alembic commands ###
