"""Added new column

Revision ID: f280c16c5ccd
Revises: 732ede14bd06
Create Date: 2026-02-02 15:22:19.582715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f280c16c5ccd'
down_revision: Union[str, Sequence[str], None] = '732ede14bd06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pgsqldocument', sa.Column('document_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pgsqldocument', 'document_type')
    # ### end Alembic commands ###
