apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyc-service
  template:
    metadata:
      labels:
        app: kyc-service
    spec:
      containers:
        - name: kyc-service
          image: kyc-service:latest
          ports:
            - containerPort: 8000
        - name: otel-collector
          image: otel/opentelemetry-collector:latest
