"""initial setup tables

Revision ID: 87465391ba17
Revises: 
Create Date: 2026-03-10 11:33:25.924370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87465391ba17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disbursement_records',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('disbursement_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transfer_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_emi', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_interest', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_repayment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('repayment_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('receipt_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disbursement_records_application_id'), 'disbursement_records', ['application_id'], unique=False)
    op.create_table('node_audit_logs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('input_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_audit_logs')
    op.drop_index(op.f('ix_disbursement_records_application_id'), table_name='disbursement_records')
    op.drop_table('disbursement_records')
    # ### end Alembic commands ###
