services:
  kyc-agent:
    build:
      context: ..
      dockerfile: infra/docker/kyc_docker.Dockerfile
    image: kyc-agent:test
    container_name: kyc-agent-container

    ports:
      - "8001:8001"

    env_file:
      - ../.env
    
    volumes:
      - ../src:/app/src   # optional (for development)

    restart: unless-stopped