"""response store

Revision ID: 7a28723bdf31
Revises: f712cdc80034
Create Date: 2026-03-23 12:49:39.295123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a28723bdf31'
down_revision: Union[str, Sequence[str], None] = 'f712cdc80034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('underwriting_decisions', sa.Column('disbursement_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('underwriting_decisions', sa.Column('decline_reason', sa.Text(), nullable=True))
    op.add_column('underwriting_decisions', sa.Column('counter_offer_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('underwriting_decisions', sa.Column('thread_id', sa.String(length=100), nullable=True))
    op.add_column('underwriting_decisions', sa.Column('execution_time_ms', sa.BigInteger(), nullable=True))
    op.add_column('underwriting_decisions', sa.Column('parallel_tasks_executed', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('underwriting_decisions', sa.Column('node_execution_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('underwriting_decisions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.drop_index(op.f('ix_underwriting_decisions_correlation_id'), table_name='underwriting_decisions')
    op.drop_column('underwriting_decisions', 'correlation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('underwriting_decisions', sa.Column('correlation_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_underwriting_decisions_correlation_id'), 'underwriting_decisions', ['correlation_id'], unique=False)
    op.drop_column('underwriting_decisions', 'updated_at')
    op.drop_column('underwriting_decisions', 'node_execution_times')
    op.drop_column('underwriting_decisions', 'parallel_tasks_executed')
    op.drop_column('underwriting_decisions', 'execution_time_ms')
    op.drop_column('underwriting_decisions', 'thread_id')
    op.drop_column('underwriting_decisions', 'counter_offer_data')
    op.drop_column('underwriting_decisions', 'decline_reason')
    op.drop_column('underwriting_decisions', 'disbursement_amount')
    # ### end Alembic commands ###
