"""initial setup tables

Revision ID: a70c9a5e17ba
Revises: d2ed7c88a582
Create Date: 2026-03-10 11:23:31.596804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a70c9a5e17ba'
down_revision: Union[str, Sequence[str], None] = 'd2ed7c88a582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('underwriting_decisions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('risk_tier', sa.String(length=10), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('reasoning_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_decision_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_underwriting_decisions_application_id'), 'underwriting_decisions', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_underwriting_decisions_application_id'), table_name='underwriting_decisions')
    op.drop_table('underwriting_decisions')
    # ### end Alembic commands ###
