"""initial setup

Revision ID: d2ed7c88a582
Revises: 64f07a99aea1
Create Date: 2026-03-10 11:22:31.636741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2ed7c88a582'
down_revision: Union[str, Sequence[str], None] = '64f07a99aea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_audit_logs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('input_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_audit_logs')
    # ### end Alembic commands ###
