"""table split

Revision ID: 03427b68d3ce
Revises: 5ded3a69d5d7
Create Date: 2026-02-16 15:38:10.800898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03427b68d3ce'
down_revision: Union[str, Sequence[str], None] = '5ded3a69d5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_idempotency',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_idempotency_idempotency_key'), 'kyc_idempotency', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_kyc_idempotency_kyc_id'), 'kyc_idempotency', ['kyc_id'], unique=True)
    op.create_index(op.f('ix_kyc_idempotency_payload_hash'), 'kyc_idempotency', ['payload_hash'], unique=False)
    op.drop_index(op.f('ix_kyc_attempts_payload_hash'), table_name='kyc_attempts')
    op.drop_constraint(op.f('kyc_attempts_idempotency_key_key'), 'kyc_attempts', type_='unique')
    op.drop_column('kyc_attempts', 'idempotency_key')
    op.drop_column('kyc_attempts', 'shadow_decision_status')
    op.drop_column('kyc_attempts', 'payload_hash')
    op.drop_column('kyc_attempts', 'rules_version')
    op.drop_column('kyc_attempts', 'attempt_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_attempts', sa.Column('attempt_version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('kyc_attempts', sa.Column('rules_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('kyc_attempts', sa.Column('payload_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('kyc_attempts', sa.Column('shadow_decision_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('kyc_attempts', sa.Column('idempotency_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('kyc_attempts_idempotency_key_key'), 'kyc_attempts', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_kyc_attempts_payload_hash'), 'kyc_attempts', ['payload_hash'], unique=False)
    op.drop_index(op.f('ix_kyc_idempotency_payload_hash'), table_name='kyc_idempotency')
    op.drop_index(op.f('ix_kyc_idempotency_kyc_id'), table_name='kyc_idempotency')
    op.drop_index(op.f('ix_kyc_idempotency_idempotency_key'), table_name='kyc_idempotency')
    op.drop_table('kyc_idempotency')
    # ### end Alembic commands ###
