"""col correction

Revision ID: 2e95c53a139f
Revises: 60fd50b31568
Create Date: 2026-02-17 16:27:52.156648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e95c53a139f'
down_revision: Union[str, Sequence[str], None] = '60fd50b31568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address_verifications', 'standardized')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_verifications', sa.Column('standardized', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
