"""identity_check

Revision ID: 3bbb19900911
Revises: 6149d6c5cd4b
Create Date: 2026-02-23 15:23:29.206294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bbb19900911'
down_revision: Union[str, Sequence[str], None] = '6149d6c5cd4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kyc_id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.String(), nullable=False),
    sa.Column('final_status', sa.String(), nullable=False),
    sa.Column('risk_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identity_checks')
    # ### end Alembic commands ###
