"""SSN and address split

Revision ID: 60fd50b31568
Revises: cc5f8fca9d0c
Create Date: 2026-02-17 16:25:53.635204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60fd50b31568'
down_revision: Union[str, Sequence[str], None] = 'cc5f8fca9d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_verifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_id', sa.UUID(), nullable=False),
    sa.Column('address_match', sa.Boolean(), nullable=True),
    sa.Column('standardized', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('geo_risk_flag', sa.Boolean(), nullable=True),
    sa.Column('high_risk_country_flag', sa.Boolean(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('address_type', sa.String(length=50), nullable=False),
    sa.Column('usps_validated', sa.Boolean(), nullable=False),
    sa.Column('deliverable', sa.Boolean(), nullable=True),
    sa.Column('standardized_address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_verifications_kyc_id'), 'address_verifications', ['kyc_id'], unique=True)
    op.create_table('ssn_validations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_id', sa.UUID(), nullable=False),
    sa.Column('ssn_valid', sa.Boolean(), nullable=True),
    sa.Column('ssn_plausible', sa.Boolean(), nullable=True),
    sa.Column('identity_theft_flag', sa.Boolean(), nullable=True),
    sa.Column('ssn_score', sa.Float(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name_ssn_match', sa.Boolean(), nullable=True, comment='Indicates whether applicant name matches SSN record.'),
    sa.Column('dob_ssn_match', sa.Boolean(), nullable=True, comment='Indicates whether applicant date of birth matches SSN record.'),
    sa.Column('issued_year', sa.Integer(), nullable=True, comment='Approximate year SSN was issued (used for fraud pattern detection).'),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssn_validations_kyc_id'), 'ssn_validations', ['kyc_id'], unique=True)
    op.drop_index(op.f('ix_identity_checks_kyc_id'), table_name='identity_checks')
    op.drop_table('identity_checks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_checks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('kyc_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ssn_valid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ssn_plausible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('name_dob_match', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('address_match', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('phone_match', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_match', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('identity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc_cases.id'], name=op.f('identity_checks_kyc_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('identity_checks_pkey'))
    )
    op.create_index(op.f('ix_identity_checks_kyc_id'), 'identity_checks', ['kyc_id'], unique=True)
    op.drop_index(op.f('ix_ssn_validations_kyc_id'), table_name='ssn_validations')
    op.drop_table('ssn_validations')
    op.drop_index(op.f('ix_address_verifications_kyc_id'), table_name='address_verifications')
    op.drop_table('address_verifications')
    # ### end Alembic commands ###
