"""col alter

Revision ID: 6149d6c5cd4b
Revises: cf2d9d3f00de
Create Date: 2026-02-20 15:31:13.796582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6149d6c5cd4b'
down_revision: Union[str, Sequence[str], None] = 'cf2d9d3f00de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():

    # 1️⃣ add column nullable first
    op.add_column(
        "kyc_cases",
        sa.Column("raw_request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )

    # 2️⃣ backfill existing rows (very important)
    op.execute(
        """
        UPDATE kyc_cases
        SET raw_request_payload = '{}'::jsonb
        WHERE raw_request_payload IS NULL
        """
    )

    # 3️⃣ make NOT NULL
    op.alter_column(
        "kyc_cases",
        "raw_request_payload",
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc_cases', 'raw_request_payload')
    # ### end Alembic commands ###
