"""kyc db setup

Revision ID: 8614c9091327
Revises: 
Create Date: 2026-02-16 13:05:23.308417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8614c9091327'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'HUMAN', name='actor_type_enum'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('audit_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('attempt_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PASSED', 'REVIEW', 'FAILED', name='kyc_status_enum'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('rules_version', sa.String(length=50), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('shadow_decision_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_kyc_attempts_application_id'), 'kyc_attempts', ['application_id'], unique=False)
    op.create_table('aml_checks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_attempt_id', sa.UUID(), nullable=False),
    sa.Column('ofac_match', sa.Boolean(), nullable=True),
    sa.Column('ofac_confidence', sa.Float(), nullable=True),
    sa.Column('pep_match', sa.Boolean(), nullable=True),
    sa.Column('sanctions_list_version', sa.String(length=100), nullable=True),
    sa.Column('aml_score', sa.Float(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kyc_attempt_id'], ['kyc_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aml_checks_kyc_attempt_id'), 'aml_checks', ['kyc_attempt_id'], unique=True)
    op.create_index(op.f('ix_aml_checks_ofac_match'), 'aml_checks', ['ofac_match'], unique=False)
    op.create_table('document_checks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_attempt_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('issuer_valid', sa.Boolean(), nullable=True),
    sa.Column('expiry_valid', sa.Boolean(), nullable=True),
    sa.Column('tamper_detected', sa.Boolean(), nullable=True),
    sa.Column('format_valid', sa.Boolean(), nullable=True),
    sa.Column('document_score', sa.Float(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kyc_attempt_id'], ['kyc_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kyc_attempt_id')
    )
    op.create_table('evidence_artifacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_attempt_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.Enum('ID_IMAGE', 'SELFIE', 'VENDOR_JSON', 'LOG_SNAPSHOT', name='artifact_type_enum'), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('file_hash', sa.String(length=255), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kyc_attempt_id'], ['kyc_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('face_checks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_attempt_id', sa.UUID(), nullable=False),
    sa.Column('face_match_score', sa.Float(), nullable=True),
    sa.Column('liveness_passed', sa.Boolean(), nullable=True),
    sa.Column('spoof_detected', sa.Boolean(), nullable=True),
    sa.Column('face_threshold', sa.Float(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kyc_attempt_id'], ['kyc_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kyc_attempt_id')
    )
    op.create_table('identity_checks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_attempt_id', sa.UUID(), nullable=False),
    sa.Column('ssn_valid', sa.Boolean(), nullable=False),
    sa.Column('ssn_plausible', sa.Boolean(), nullable=False),
    sa.Column('name_dob_match', sa.Boolean(), nullable=False),
    sa.Column('address_match', sa.Boolean(), nullable=False),
    sa.Column('phone_match', sa.Boolean(), nullable=False),
    sa.Column('email_match', sa.Boolean(), nullable=False),
    sa.Column('identity_score', sa.Float(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_attempt_id'], ['kyc_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kyc_attempt_id')
    )
    op.create_table('risk_decisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_attempt_id', sa.UUID(), nullable=False),
    sa.Column('final_status', sa.Enum('PASS', 'REVIEW', 'FAIL', name='decision_enum'), nullable=False),
    sa.Column('aggregated_score', sa.Float(), nullable=True),
    sa.Column('hard_fail_triggered', sa.Boolean(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decision_rules_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kyc_attempt_id'], ['kyc_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kyc_attempt_id')
    )
    op.create_table('vendor_responses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_attempt_id', sa.UUID(), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=True),
    sa.Column('vendor_service', sa.String(length=100), nullable=True),
    sa.Column('response_hash', sa.String(length=255), nullable=True),
    sa.Column('raw_response_location', sa.String(length=500), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kyc_attempt_id'], ['kyc_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_responses')
    op.drop_table('risk_decisions')
    op.drop_table('identity_checks')
    op.drop_table('face_checks')
    op.drop_table('evidence_artifacts')
    op.drop_table('document_checks')
    op.drop_index(op.f('ix_aml_checks_ofac_match'), table_name='aml_checks')
    op.drop_index(op.f('ix_aml_checks_kyc_attempt_id'), table_name='aml_checks')
    op.drop_table('aml_checks')
    op.drop_index(op.f('ix_kyc_attempts_application_id'), table_name='kyc_attempts')
    op.drop_table('kyc_attempts')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
