"""vendor callback change

Revision ID: 88461e14a559
Revises: f7e78654818e
Create Date: 2026-03-03 18:37:30.770831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88461e14a559'
down_revision: Union[str, Sequence[str], None] = 'f7e78654818e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_cases', sa.Column('vendor_transaction_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_kyc_cases_vendor_transaction_id'), 'kyc_cases', ['vendor_transaction_id'], unique=False)
    op.add_column('vendor_responses', sa.Column('vendor_transaction_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_vendor_responses_response_hash'), 'vendor_responses', ['response_hash'], unique=False)
    op.create_index(op.f('ix_vendor_responses_vendor_transaction_id'), 'vendor_responses', ['vendor_transaction_id'], unique=False)
    op.create_unique_constraint('uq_vendor_txn_per_vendor', 'vendor_responses', ['vendor_name', 'vendor_transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vendor_txn_per_vendor', 'vendor_responses', type_='unique')
    op.drop_index(op.f('ix_vendor_responses_vendor_transaction_id'), table_name='vendor_responses')
    op.drop_index(op.f('ix_vendor_responses_response_hash'), table_name='vendor_responses')
    op.drop_column('vendor_responses', 'vendor_transaction_id')
    op.drop_index(op.f('ix_kyc_cases_vendor_transaction_id'), table_name='kyc_cases')
    op.drop_column('kyc_cases', 'vendor_transaction_id')
    # ### end Alembic commands ###
