"""node audit

Revision ID: b7237fe0274c
Revises: 88461e14a559
Create Date: 2026-03-17 13:06:00.054992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7237fe0274c'
down_revision: Union[str, Sequence[str], None] = '88461e14a559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_audit_logs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('input_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_kyc_cases_vendor_transaction_id'), table_name='kyc_cases')
    op.drop_column('kyc_cases', 'vendor_transaction_id')
    op.drop_index(op.f('ix_vendor_responses_response_hash'), table_name='vendor_responses')
    op.drop_index(op.f('ix_vendor_responses_vendor_transaction_id'), table_name='vendor_responses')
    op.drop_constraint(op.f('uq_vendor_txn_per_vendor'), 'vendor_responses', type_='unique')
    op.drop_column('vendor_responses', 'vendor_transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_responses', sa.Column('vendor_transaction_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_vendor_txn_per_vendor'), 'vendor_responses', ['vendor_name', 'vendor_transaction_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_vendor_responses_vendor_transaction_id'), 'vendor_responses', ['vendor_transaction_id'], unique=False)
    op.create_index(op.f('ix_vendor_responses_response_hash'), 'vendor_responses', ['response_hash'], unique=False)
    op.add_column('kyc_cases', sa.Column('vendor_transaction_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_kyc_cases_vendor_transaction_id'), 'kyc_cases', ['vendor_transaction_id'], unique=False)
    op.drop_table('node_audit_logs')
    # ### end Alembic commands ###
