"""new db setup

Revision ID: cc5f8fca9d0c
Revises: 
Create Date: 2026-02-16 17:12:24.258503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc5f8fca9d0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'HUMAN', name='actor_type_enum'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('audit_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_cases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PASSED', 'REVIEW', 'FAILED', name='kyc_status_enum'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('rules_version', sa.String(length=50), nullable=True),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('threshold_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_cases_applicant_id'), 'kyc_cases', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_kyc_cases_created_at'), 'kyc_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_kyc_cases_payload_hash'), 'kyc_cases', ['payload_hash'], unique=False)
    op.create_index(op.f('ix_kyc_cases_status'), 'kyc_cases', ['status'], unique=False)
    op.create_table('aml_checks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_id', sa.UUID(), nullable=False),
    sa.Column('ofac_match', sa.Boolean(), nullable=True),
    sa.Column('ofac_confidence', sa.Float(), nullable=True),
    sa.Column('pep_match', sa.Boolean(), nullable=True),
    sa.Column('sanctions_list_version', sa.String(length=100), nullable=True),
    sa.Column('aml_score', sa.Float(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aml_checks_kyc_id'), 'aml_checks', ['kyc_id'], unique=True)
    op.create_index(op.f('ix_aml_checks_ofac_match'), 'aml_checks', ['ofac_match'], unique=False)
    op.create_table('document_checks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('issuer_valid', sa.Boolean(), nullable=True),
    sa.Column('expiry_valid', sa.Boolean(), nullable=True),
    sa.Column('tamper_detected', sa.Boolean(), nullable=True),
    sa.Column('format_valid', sa.Boolean(), nullable=True),
    sa.Column('document_score', sa.Float(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('document_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issuing_country', sa.String(length=50), nullable=True),
    sa.Column('issuing_state', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_checks_kyc_id'), 'document_checks', ['kyc_id'], unique=True)
    op.create_table('evidence_artifacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.Enum('ID_IMAGE', 'SELFIE', 'VENDOR_JSON', 'LOG_SNAPSHOT', name='artifact_type_enum'), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=255), nullable=True),
    sa.Column('additional_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_artifacts_artifact_type'), 'evidence_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_evidence_artifacts_kyc_id'), 'evidence_artifacts', ['kyc_id'], unique=False)
    op.create_table('face_checks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_id', sa.UUID(), nullable=False),
    sa.Column('face_match_score', sa.Float(), nullable=True),
    sa.Column('liveness_passed', sa.Boolean(), nullable=True),
    sa.Column('liveness_score', sa.Float(), nullable=True),
    sa.Column('spoof_detected', sa.Boolean(), nullable=True),
    sa.Column('face_threshold', sa.Float(), nullable=True),
    sa.Column('face_detection_confidence', sa.Float(), nullable=True),
    sa.Column('deepfake_score', sa.Float(), nullable=True),
    sa.Column('replay_attack_detected', sa.Boolean(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_checks_kyc_id'), 'face_checks', ['kyc_id'], unique=True)
    op.create_table('human_reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'REUPLOAD_REQUESTED', name='human_review_decision_enum'), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('review_reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_reviews_created_at'), 'human_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_human_reviews_decision'), 'human_reviews', ['decision'], unique=False)
    op.create_index(op.f('ix_human_reviews_kyc_id'), 'human_reviews', ['kyc_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_reviewer_id'), 'human_reviews', ['reviewer_id'], unique=False)
    op.create_table('identity_checks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_id', sa.UUID(), nullable=False),
    sa.Column('ssn_valid', sa.Boolean(), nullable=True),
    sa.Column('ssn_plausible', sa.Boolean(), nullable=True),
    sa.Column('name_dob_match', sa.Boolean(), nullable=True),
    sa.Column('address_match', sa.Boolean(), nullable=True),
    sa.Column('phone_match', sa.Boolean(), nullable=True),
    sa.Column('email_match', sa.Boolean(), nullable=True),
    sa.Column('identity_score', sa.Float(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_checks_kyc_id'), 'identity_checks', ['kyc_id'], unique=True)
    op.create_table('kyc_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('kyc_id', sa.UUID(), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='idempotency_status_enum'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_requests_idempotency_key'), 'kyc_requests', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_kyc_requests_kyc_id'), 'kyc_requests', ['kyc_id'], unique=False)
    op.create_index(op.f('ix_kyc_requests_payload_hash'), 'kyc_requests', ['payload_hash'], unique=False)
    op.create_table('risk_decisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_id', sa.UUID(), nullable=False),
    sa.Column('final_status', sa.Enum('PASS', 'REVIEW', 'FAIL', name='decision_enum'), nullable=False),
    sa.Column('aggregated_score', sa.Float(), nullable=True),
    sa.Column('hard_fail_triggered', sa.Boolean(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decision_rules_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_decisions_created_at'), 'risk_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_decisions_final_status'), 'risk_decisions', ['final_status'], unique=False)
    op.create_index(op.f('ix_risk_decisions_kyc_id'), 'risk_decisions', ['kyc_id'], unique=True)
    op.create_table('vendor_responses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_id', sa.UUID(), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=False),
    sa.Column('vendor_service', sa.String(length=100), nullable=True),
    sa.Column('response_hash', sa.String(length=255), nullable=True),
    sa.Column('raw_response_location', sa.String(length=500), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('request_payload_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_responses_kyc_id'), 'vendor_responses', ['kyc_id'], unique=False)
    op.create_index(op.f('ix_vendor_responses_vendor_name'), 'vendor_responses', ['vendor_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_responses_vendor_name'), table_name='vendor_responses')
    op.drop_index(op.f('ix_vendor_responses_kyc_id'), table_name='vendor_responses')
    op.drop_table('vendor_responses')
    op.drop_index(op.f('ix_risk_decisions_kyc_id'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_final_status'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_created_at'), table_name='risk_decisions')
    op.drop_table('risk_decisions')
    op.drop_index(op.f('ix_kyc_requests_payload_hash'), table_name='kyc_requests')
    op.drop_index(op.f('ix_kyc_requests_kyc_id'), table_name='kyc_requests')
    op.drop_index(op.f('ix_kyc_requests_idempotency_key'), table_name='kyc_requests')
    op.drop_table('kyc_requests')
    op.drop_index(op.f('ix_identity_checks_kyc_id'), table_name='identity_checks')
    op.drop_table('identity_checks')
    op.drop_index(op.f('ix_human_reviews_reviewer_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_kyc_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_decision'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_created_at'), table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_index(op.f('ix_face_checks_kyc_id'), table_name='face_checks')
    op.drop_table('face_checks')
    op.drop_index(op.f('ix_evidence_artifacts_kyc_id'), table_name='evidence_artifacts')
    op.drop_index(op.f('ix_evidence_artifacts_artifact_type'), table_name='evidence_artifacts')
    op.drop_table('evidence_artifacts')
    op.drop_index(op.f('ix_document_checks_kyc_id'), table_name='document_checks')
    op.drop_table('document_checks')
    op.drop_index(op.f('ix_aml_checks_ofac_match'), table_name='aml_checks')
    op.drop_index(op.f('ix_aml_checks_kyc_id'), table_name='aml_checks')
    op.drop_table('aml_checks')
    op.drop_index(op.f('ix_kyc_cases_status'), table_name='kyc_cases')
    op.drop_index(op.f('ix_kyc_cases_payload_hash'), table_name='kyc_cases')
    op.drop_index(op.f('ix_kyc_cases_created_at'), table_name='kyc_cases')
    op.drop_index(op.f('ix_kyc_cases_applicant_id'), table_name='kyc_cases')
    op.drop_table('kyc_cases')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
