"""col add

Revision ID: cf2d9d3f00de
Revises: 2e95c53a139f
Create Date: 2026-02-17 18:52:00.964054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2d9d3f00de'
down_revision: Union[str, Sequence[str], None] = '2e95c53a139f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ssn_validations', sa.Column('deceased_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ssn_validations', 'deceased_flag')
    # ### end Alembic commands ###
