"""added new table

Revision ID: d1f074d4de0d
Revises: fa4e0b9e0187
Create Date: 2026-02-16 14:52:18.097892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f074d4de0d'
down_revision: Union[str, Sequence[str], None] = 'fa4e0b9e0187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kyc_attempt_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'REUPLOAD_REQUESTED', name='human_review_decision_enum'), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_attempt_id'], ['kyc_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_reviews_kyc_attempt_id'), 'human_reviews', ['kyc_attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_reviews_kyc_attempt_id'), table_name='human_reviews')
    op.drop_table('human_reviews')
    # ### end Alembic commands ###
