"""identity checks updated

Revision ID: f7e78654818e
Revises: 3bbb19900911
Create Date: 2026-02-24 14:18:49.873877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7e78654818e'
down_revision: Union[str, Sequence[str], None] = '3bbb19900911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identity_checks', sa.Column('aggregated_score', sa.Float(), nullable=True))
    op.add_column('identity_checks', sa.Column('hard_fail_triggered', sa.Boolean(), nullable=True))
    op.add_column('identity_checks', sa.Column('ssn_valid', sa.Boolean(), nullable=True))
    op.add_column('identity_checks', sa.Column('ssn_plausible', sa.Boolean(), nullable=True))
    op.add_column('identity_checks', sa.Column('name_ssn_match', sa.Boolean(), nullable=True))
    op.add_column('identity_checks', sa.Column('dob_ssn_match', sa.Boolean(), nullable=True))
    op.add_column('identity_checks', sa.Column('deceased_flag', sa.Boolean(), nullable=True))
    op.add_column('identity_checks', sa.Column('ssn_risk_snapshot', sa.JSON(), nullable=True))
    op.add_column('identity_checks', sa.Column('decision_rules_snapshot', sa.JSON(), nullable=True))
    op.add_column('identity_checks', sa.Column('model_versions', sa.JSON(), nullable=True))
    op.add_column('identity_checks', sa.Column('audit_payload', sa.JSON(), nullable=True))
    op.add_column('identity_checks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('identity_checks', 'risk_payload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identity_checks', sa.Column('risk_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('identity_checks', 'created_at')
    op.drop_column('identity_checks', 'audit_payload')
    op.drop_column('identity_checks', 'model_versions')
    op.drop_column('identity_checks', 'decision_rules_snapshot')
    op.drop_column('identity_checks', 'ssn_risk_snapshot')
    op.drop_column('identity_checks', 'deceased_flag')
    op.drop_column('identity_checks', 'dob_ssn_match')
    op.drop_column('identity_checks', 'name_ssn_match')
    op.drop_column('identity_checks', 'ssn_plausible')
    op.drop_column('identity_checks', 'ssn_valid')
    op.drop_column('identity_checks', 'hard_fail_triggered')
    op.drop_column('identity_checks', 'aggregated_score')
    # ### end Alembic commands ###
