"""added column

Revision ID: fa4e0b9e0187
Revises: 8614c9091327
Create Date: 2026-02-16 14:08:45.364304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4e0b9e0187'
down_revision: Union[str, Sequence[str], None] = '8614c9091327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_attempts', sa.Column('payload_hash', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_kyc_attempts_payload_hash'), 'kyc_attempts', ['payload_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kyc_attempts_payload_hash'), table_name='kyc_attempts')
    op.drop_column('kyc_attempts', 'payload_hash')
    # ### end Alembic commands ###
